import { simplifyTopicsWithChatGPT, imageGenApiCall, getComplexInfoFromTopic} from './OpenAI.js';

// Test simplifyTopicsWithChatGPT
const testSimplifyTopics = async () => {
    const text = "Reading Selections Early Settlers in North America The North and South American continents were not always home to the many different peoples who live here today. Ancient people migrated from Asia many thousands of years ago, traveling throughout North and South America, carrying their cultures with them and adapting to the lands they discov- ered. Historians believe these people walked across asmall \
    bridge of land that is now covered by water. Today we call it the Bering Strait. The First Nations Many of these travelers from Asia settled all over North America. We know their descendants as Indigenous people (also called, depending on the region, First Peoples, First Nations, Native Americans, and American Indians). Long before people crossed the Bering Strait and popu- lated North and South America, wild horses lived \
    on the North American continent. Their fossils have been found by scientists. Very early horses were quite different from the horses we see today: they were only one foot tall! No one knows why, but these horses disappeared, maybe by traveling across the Bering Strait, or perhaps because major changes in the cli- mate caused them to die out. There were no more horses in North or South America until Spanish explorers brought them in the 1500s.\
    As is the case all over the world, the people who populated North and South America lived in many different ways, developing their particular cultures and lifestyles in relationship to their environment. In fourth grade you probably studied the Indigenous people in the area where you live. First Nations all over the continent had different ways of adapting to what was around them. The Great Plains tribes depended on the buffalo, which is also called American bison. They built homes either of sod or buffalo skin; Indigenous people in the Northwest lived in homes made of wood and bark, \
    and those on the coast were fish- ermen; the Arctic First Nations depended on ice, seals, and whales. Grade 5 English/United States History Lesson 1 Oak Meadow 7 Later, when horses became re-established in North America, they made a huge difference in the lives of many Indigenous tribes. The ability to ride horses meant people could cover many miles in a short time. Horses could be used to carry supplies and pull carts of different kinds. Horses also changed the way some Indigenous people engaged in battle and hunted. After crossing the Bering Strait, the new inhabitants of North America were left alone for a very long time. Then, around 1,000 years ago, the first Europeans came to explore the continent. They were Vikings from the part of the world that is now Norway, Iceland, and Greenland. It is amazing to think of these people traveling so far across the ocean because the Viking boats \
    were open—they didnt have closed areas, like the boats that crossed the ocean from Europe much later. Remains of a Viking camp have been found on the island of Newfoundland, and historians think that an adventurer named Leif Erickson started a settlement there. Erickson and his crew found grapevines, and named their camp Vineland or Vinland after the grapes. The story of Ericksons adventures (and the explorations of his father before him and his daughter after him) was passed down through many generations of Vikings and eventually written down. Some is myth, but some no doubt actually happened. Of course, many facts are missing, and we still dont really know why the Vikings left their settlement in North America. About 500 years went by between the Vikings visit and the arrival of more Europeans. The European Age of Exploration It is impossible to study the beginnings of the United States of America without looking back to the European Age of Exploration. Europeans became interested in exploring the world during a series of wars called the Crusades. \
    The Crusades were reli- gious wars that were fought between the years 1100 and 1300. During the Crusades, many Europeans traveled to the Middle East and Asia to fight, and while they were there they became interested in the fascinating things they saw and experienced. The more they saw, the more they wanted to explore. The soldiers brought home unusual artifacts, gems, silks, spices, and other wonderful things. It was clear there was money to be made and adventures to be had. So began the Age of Exploration. Marco Polo was an Italian explorer who traveled in Asia in the late 1200s and early 1300s. He told remarkable stories of his adventures, some of which were probably not true or greatly exaggerated. His book, Description of the World, written in 1298, became the most popular book in Europe, and the more people heard about his adventures, the more they wanted to see Asia for themselves. Europeans also wanted to travel to spread their religion. They believed it was their duty to convince all non-Christians to become Christians. Between their interest in trade and their desire to do their reli- gious duty, they were very eager to find routes to new and fascinating places. Lesson 1 Grade 5 English/United States History 8 Oak Meadow Early Navigation Before the Age of Exploration, most\
    Europeans didnt know very much about the world beyond their own towns. Many people believed there were monsters in the ocean, or that the world was flat, and that if a ship sailed too far it would fall right off the edge of the world. Some people thought parts of the ocean were filled with boiling water. Of course, when more adventurers set off across the seas and came home safely, these beliefs began to change. Sailing was dangerous in those days. There were no monsters in the seas, but there were strong cur- rents, rocks, and other hazards, just as there are today. Ships sailed by wind power, and were often blown off course. Today, we have lots of technological help to get from one continent or island to another. Early explorers did not have any fancy technology to help them find their way. But they knew how to find directions. North, south, east, and west are the main, or cardinal, directions. If you can find north, you can also find east, south, and west. When you face north, south is behind you, east is to the right, and west is to the left. In the middle of the ocean, theres nothing to look at that isnt moving, so its hard to tell what direction you are going. Its important to have a “fixed point.” Sailors in the Northern Hemisphere steered by the stars, using the North Star as their fixed point. The sun and the North Star were valu- able tools because the sun always rises in the east and sets in the west, and the North Star stays in almost exactly the same place all the time. There are three ways to find north. On a sunny day you can use shadows. (If you are in the United States, your shadow always points\
    north at noon on a sunny day.) On a clear night you can use the North Star if you live in the Northern Hemisphere. Lastly, you can always find north using a compass. Place the compass flat on a table and turn it so that the letter N and the point of the needle are at the same place. Now the compass is pointing north. Grade 5 English/United States History Lesson 1 Oak Meadow 9 The North Star is always in the north. It is not very large or bright, but, unlike the other heavenly bod- ies, it stays in basically the same place. A group of seven stars called the Big Dipper will help you to find the North Star. Although the Big Dipper may be above the North Star at times, and at other times to the right, left, or below it, two stars on the outer edge of the Big Dipper always point to the North Star. These two stars are called pointers. A straight line drawn through the pointers will lead directly to the North Star. The North Star is the last star in the handle of another constellation called the Little Dipper. As time went on and more expeditions set forth from the countries of Europe, new ships were built that had adjustable masts, sails, and rudders, which helped sailors stay on course. A tool called a cross- staff was used to help figure out a ships location by lining up the North Star with one part of the cross and the horizon with the other part. This allowed sailors to determine how far north or south they were, but they still had no good way to tell how far east or west they were. Today we have maps and globes to tell us what the Earth looks like. The globe is a spherical map. Half a globe is called a hemisphere (which means “half-sphere”). If we divide the Earth evenly, with an east- west line, we have a Northern Hemisphere \
    and a Southern Hemisphere. If we divide the Earth evenly on a north-south line, we have an Eastern Hemisphere and a Western Hemisphere.";
    const num_captions = 8;

    const result = await simplifyTopicsWithChatGPT(text, num_captions);
    console.log(result);
};

// Test imageGenApiCall
const testImageGen = async () => {
    const text = "Reading Selections Early Settlers in North America...";
    const num_captions = 8;
  
    const captionsResult = await simplifyTopicsWithChatGPT(text, num_captions);
    if (captionsResult.success) {
      const captions = captionsResult.data;
      const complex = await getComplexInfoFromTopic(text, captions)
      console.log(complex);
      const result = await imageGenApiCall(captions);
      console.log(result);
    } else {
      console.log('Error in simplifyTopicsWithChatGPT:', captionsResult.msg);
    }
  };
  
  // Run tests
  (async () => {
    await testSimplifyTopics();
    await testImageGen();
  })();